name: Lint, Test and Deploy Workflow 1
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get github repository.
      - uses: actions/checkout@v3
      - name: Install package dependencies
      - run: npm ci
      - name: Lint code
      - run: npm run lint
      - name: Test code
      - run: npm run test
      - name: Build code
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get github repository.
      - uses: actions/checkout@v3
      - name: Install package dependencies
      - run: npm ci
      - name: Test code
      - run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get github repository.
      - uses: actions/checkout@v3
      - name: Install package dependencies
      - run: npm ci
      - name: Build code
      - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to hosting provider
      - run: echo "Deploying to hosting provider "
